# coding: utf-8

"""
    aind-active-directory-service

     ## aind-active-directory-service  Service to pull data from Microsoft Active Directory.  

    The version of the OpenAPI document: 0.1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_active_directory_service_async_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.IsolatedAsyncioTestCase):
    """DefaultApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = DefaultApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_user_from_active_directory(self) -> None:
        """Test case for get_user_from_active_directory

        Get User From Active Directory
        """
        pass


if __name__ == '__main__':
    unittest.main()
